### ISSUE TITLE
new website redirect problem

### ISSUE THREAD

**Issue by aardbluefeather** [aardlyworthit/winds_trading#1]
Hey, sorry to bother you here, but I'm not really sure on how to reach you otherwise... It's not really a problem with this plugin, but rather with the website this plugin connects to.

- after the manual case upload (via "Upload My Cases/Cards") - the upload.php tries to redirect browser to the old website which is no longer in use
- at the /case/edit page, clicking on links "Upload My Extra Cards" or "View My Cases/Cards" also links to old website
- top link on yellow background, linking to raw xml plugin is missing a "l" in "...xml" at the end, so it's throwing a 404

Thanks,
BlueFeather

**Comment by aardlyworthit** [comment]
Hey I just got this email. Sorry I haven't checked it in a long time. I
updated the plugin source when I changed the URL. I assume you figured that
out already but didn't want to leave you hanging (longer). The website was
also updated, but possibly had some bad links at first. I didn't see any
current bad links...
